apiVersion: v1
kind: PersistentVolume
metadata:
 name: bungee
spec:
 capacity:
  storage: 5Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/minecraft-server/bungee
